### ISSUE TITLE
Avoir le même design pour les issues que pour les repos

### ISSUE THREAD

**Issue by Gillespie59** [T3kstiil3/github_report_dashboard#10]
![image](https://cloud.githubusercontent.com/assets/555768/24401426/a55de700-13b4-11e7-8d55-58dbc5a0c466.png)

**Comment by T3kstiil3** [comment]
![image](https://cloud.githubusercontent.com/assets/3717296/24403287/7a40948e-13bc-11e7-969b-fa529aaf58e8.png)
