### ISSUE TITLE
Chrome Extension

### ISSUE THREAD

**Issue by T3kstiil3** [T3kstiil3/github_report_dashboard#12]
Add manifest and some css to allow this app in a chrome extension

**Comment by mahasak** [comment]
@T3kstiil3 How about sizing for this extension popup ? Is this okay ?
<img width="1400" alt="screen shot 2018-10-02 at 11 43 06 am" src="https://user-images.githubusercontent.com/221276/46329593-70ef4f80-c638-11e8-86a1-882ff62c41b9.png">

**Comment by T3kstiil3** [comment]
Yes it look good. thx 🎉
