### ISSUE TITLE
[JS / Vue.js] Add google analytics

### ISSUE THREAD

**Issue by T3kstiil3** [T3kstiil3/github_report_dashboard#25]
Install analytics or vue analytics with router to have app stats

ID de suivi
```
UA-126838160-1
```

**Comment by melkyy** [comment]
i'll take this

**Comment by melkyy** [comment]
i'll take this one

**Comment by melkyy** [comment]
Can you explain me about this? I added Google Analytics in a script like this :

 `(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-126838160-1', 'auto');
    ga('send', 'pageview');` 

so i want to configure the vue route where does can add?

**Comment by T3kstiil3** [comment]
No problem 👍
Instance of use native js analytics you have to use 
- https://www.npmjs.com/package/vue-analytics
You can find example and how to use 
- https://medium.com/dailyjs/tips-tricks-for-vue-analytics-87a9d2838915

**Comment by melkyy** [comment]
I installed analytics and added the router for stats, will i need to desing the route?

**Comment by T3kstiil3** [comment]
No need to design route they are already configure 
in main.js
``
import Router from './Router'
``
Look at Router.js file :) the router is exported !

**Comment by melkyy** [comment]
this is ok?

![image](https://user-images.githubusercontent.com/28812225/46427218-b0c83c80-c6f5-11e8-998a-6797c41aaaf0.png)

will i need add this component?

![image](https://user-images.githubusercontent.com/28812225/46428045-ca6a8380-c6f7-11e8-9296-d6575cfa1750.png)

**Comment by T3kstiil3** [comment]
I don't think. Don't hesitate to do your PR, it will be more simple to comment your code 😄

**Comment by T3kstiil3** [comment]
Thx @melkyy 🎉

**Comment by melkyy** [comment]
thx for your patience and support
