### ISSUE TITLE
Use dev/prod build env variable

### ISSUE THREAD

**Issue by T3kstiil3** [T3kstiil3/github_report_dashboard#3]
Use dev/prod build env variable

**front/env.js**
![image](https://cloud.githubusercontent.com/assets/3717296/24345502/c9c1c8b2-12d0-11e7-9d4c-e3be6bc10ad5.png)

**Comment by Gillespie59** [comment]
Faut utiliser NODE_ENV pour le back et le front. 
Et ensuite trouver le bon plugin Webpack pour importer les bon fichier en fonction de la variable d'environnement
