### ISSUE TITLE
Formatter la date avec momentjs

### ISSUE THREAD

**Issue by Gillespie59** [T3kstiil3/github_report_dashboard#6]
![image](https://cloud.githubusercontent.com/assets/555768/24401223/cb69bace-13b3-11e7-8773-48db4577f4e5.png)

**Comment by T3kstiil3** [comment]
![image](https://cloud.githubusercontent.com/assets/3717296/24403807/d1baa9e6-13be-11e7-8b25-bf4abeb84d8a.png)
