### ISSUE TITLE
Avoir des noms d'evenement plus clairs

### ISSUE THREAD

**Issue by Gillespie59** [T3kstiil3/github_report_dashboard#7]
![image](https://cloud.githubusercontent.com/assets/555768/24401255/ef616abc-13b3-11e7-9aa7-159b71e6bd98.png)

**Comment by T3kstiil3** [comment]
![image](https://cloud.githubusercontent.com/assets/3717296/24404477/ed90edbc-13c1-11e7-8f68-6e5ddfca8d49.png)
